import { useMemo, useState } from 'react';
import usePronunciationAudio from '../hooks/usePronunciationAudio';
import { createWordLookup, parseVerse } from '../utils/verseParser';
import AudioPlayerWithRate from '../components/AudioPlayerWithRate';

function VerseAssistantPage({ words }) {
  const [verseInput, setVerseInput] = useState('In those days came John the Baptist, preaching in the wilderness of Judaea.');
  const [analyzedVerse, setAnalyzedVerse] = useState('');
  const [selectedToken, setSelectedToken] = useState(null);

  const wordLookup = useMemo(() => createWordLookup(words), [words]);
  const verseTokens = useMemo(() => parseVerse(analyzedVerse, wordLookup), [analyzedVerse, wordLookup]);

  const pronunciationTarget = selectedToken
    ? selectedToken.isKnown
      ? selectedToken.matchedWord
      : {
          word: selectedToken.text,
          phonetic: '',
          category: 'Generated pronunciation',
        }
    : null;

  const { audioUrl, isLoading, errorMessage } = usePronunciationAudio(pronunciationTarget);

  const handleAnalyze = () => {
    setAnalyzedVerse(verseInput.trim());
    setSelectedToken(null);
  };

  const difficultCount = verseTokens.filter((token) => token.isWord && token.isKnown).length;

  return (
    <section className="verse-assistant fade-in">
      <header>
        <h2>Verse Assistant</h2>
        <p className="verse-subtitle">Paste a verse, highlight difficult words, and click to hear pronunciation guidance.</p>
      </header>

      <label className="search-label" htmlFor="verse-input">Verse input</label>
      <textarea
        id="verse-input"
        className="verse-input"
        rows={4}
        value={verseInput}
        onChange={(event) => setVerseInput(event.target.value)}
        placeholder="Paste a Bible verse..."
      />

      <button type="button" className="analyze-btn" onClick={handleAnalyze}>
        Analyze Verse
      </button>

      {!analyzedVerse && (
        <p className="status-message">Add a verse above and press Analyze Verse to begin.</p>
      )}

      {analyzedVerse && (
        <>
          <p className="verse-meta">Detected {difficultCount} difficult words from the pronunciation dataset.</p>
          <article className="verse-reading-layout" aria-live="polite">
            {verseTokens.map((token, index) => {
              if (!token.isWord) {
                return <span key={`text-${index}`}>{token.text}</span>;
              }

              const isSelected = selectedToken?.normalized === token.normalized && selectedToken?.text === token.text;
              return (
                <button
                  key={`word-${index}`}
                  type="button"
                  onClick={() => setSelectedToken(token)}
                  className={`verse-token ${token.isKnown ? 'known' : 'unknown'} ${isSelected ? 'selected' : ''}`}
                >
                  {token.text}
                </button>
              );
            })}
          </article>
        </>
      )}

      <section className="detail-panel verse-word-panel">
        <h3>Word pronunciation</h3>
        {!selectedToken && <p className="empty-state">Click any highlighted verse word to see details and hear audio.</p>}

        {selectedToken && (
          <>
            <p>
              <strong>Word:</strong> {selectedToken.text}
            </p>
            <p>
              <strong>Phonetic spelling:</strong>{' '}
              {selectedToken.isKnown ? selectedToken.matchedWord.phonetic : 'Generated by text-to-speech'}
            </p>
            {!selectedToken.isKnown && <p className="generated-label">generated pronunciation</p>}

            {isLoading && <p className="status-message">Generating pronunciation audio...</p>}
            {errorMessage && (
              <p className="status-message error" role="alert">
                {errorMessage}
              </p>
            )}

            {!isLoading && !errorMessage && audioUrl && (
              <div className="audio-stack">
                <AudioPlayerWithRate src={audioUrl} rate={1} label="Normal playback" />
                <AudioPlayerWithRate src={audioUrl} rate={0.75} label="Slow playback (0.75x)" />
              </div>
            )}
          </>
        )}
      </section>
    </section>
  );
}

export default VerseAssistantPage;
